apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-pod
spec:
  containers:
    - name: spring-boot-demo
      image: todo-app:latest
      imagePullPolicy: Never
    - name: mongo
      image: mongo