apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot
  template:
    spec:
      containers:
        - name: spring-boot
          image: spring-boot
   metadata:
     name: spring-boot-deployment
     labels:
       app: spring-boot