MASTER_NODES=1
WORKER_NODES=2
IP = "192.168.50."
MASTER_IP_START = 10
WORKER_IP_START = 20


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"

  (1..MASTER_NODES).each do |i|
    config.vm.define "master-#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "master-node-#{i}"
            vb.memory = 2048
            vb.cpus = 2
        end
        node.vm.hostname = "master-#{i}"
        node.vm.network "private_network", ip: IP + "#{MASTER_IP_START + i}"
        #node.vm.provision "ansible" do |ansible|
        #    ansible.playbook = "../provision/master-playbook.yaml"
        #    ansible.extra_vars = {
        #        node_ip: "192.168.50.10"
        #    }
        #end

        node.vm.provision "install-microk8s", type: "shell", :path => "../provision/microk8s-install.sh"
        #node.vm.provision "install-docker", type: "shell", :path => "../provision/docker-install.sh"
        #node.vm.provision "install-kubeadm", type: "shell", :path => "../provision/kubeadm-install.sh"
        #node.vm.provision "init-kubeadm", type: "shell", :path => "../provision/kubeadm-init-control.sh" do |s|
        #    s.args = IP + "#{MASTER_IP_START + i}"
    end
  end

  (1..WORKER_NODES).each do |i|
      config.vm.define "worker-#{i}" do |node|
         node.vm.provider "virtualbox" do |vb|
            vb.name = "worker-node-#{i}"
            vb.memory = 1024
            vb.cpus = 1
          end
          node.vm.hostname = "worker-#{i}"
          node.vm.network "private_network", ip: IP + "#{WORKER_IP_START + i}"
          #node.vm.provision "ansible" do |ansible|
          #            ansible.playbook = "../provision/node-playbook.yaml"
          #            ansible.extra_vars = {
          #                node_ip: "192.168.50.#{i}"
          #            }
          #        end
          node.vm.provision "install-microk8s", type: "shell", :path => "../provision/microk8s-install.sh"
         #node.vm.provision "install-docker", type: "shell", :path => "../provision/docker-install.sh"
         #node.vm.provision "install-kubeadm", type: "shell", :path => "../provision/kubeadm-install.sh"
      end
  end
end