MASTER_NODES=1
WORKER_NODES=1
IP = "192.168.50."
MASTER_IP_START = 10
WORKER_IP_START = 20


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/impish64"

  (1..MASTER_NODES).each do |i|
    config.vm.define "master-#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "master-node-plain-#{i}"
            vb.memory = 2048
            vb.cpus = 2
        end
        node.vm.hostname = "master-#{i}"
        node.vm.network "private_network", ip: IP + "#{MASTER_IP_START + i}"
    end
  end

  (1..WORKER_NODES).each do |i|
      config.vm.define "worker-#{i}" do |node|
         node.vm.provider "virtualbox" do |vb|
            vb.name = "worker-node-plain-#{i}"
            vb.memory = 1024
            vb.cpus = 1
          end
          node.vm.hostname = "worker-#{i}"
          node.vm.network "private_network", ip: IP + "#{WORKER_IP_START + i}"
      end
  end
end
